### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by jpadron-am** [redhat-cop/infra.controller_configuration#6]
## Summary
 
If I create the template in the GUI I am able to access the survey. The issue is when we create the template using Ansible and the infra.controller_configuration collection. When the playbook creates the template we are not able to see the survey in the GUI i to make changes. If I launch the template it does show the survey to answer. I did open a ticket with Redhat and they are having the same issue. I was told to open an issue here.
 
## Issue Type
 
- Bug Report
 
## Ansible, Collection, Controller details
 

 
```console (paste below)
ansible --version
 
ansible-galaxy collection list
infra.controller_configuration
 
Controller version
Red Hat Ansible Automation Platform
2.4
 
```
 
- ansible installation method: one of source, pip, OS package, EE
 
## Actual Behavior
 

 
Please give some details of what is actually happening.
Include a [minimum complete verifiable example] with:
The following is the error we get in the GUI:
TypeError: Cannot read properties of undefined (reading 'length')
TypeError: Cannot read properties of undefined (reading 'length') at Fle (https://ansiblecontroller-dev.company.com/static/js/main.359f10ea.js:2:3037132) at ao (https://ansiblecontroller-dev.company.com/static/js/main.359f10ea.js:2:831448) at Ks (https://ansiblecontroller-dev.company.com/static/js/main.359f10ea.js:2:883792) at Al (https://ansiblecontroller-dev.company.com/static/js/main.359f10ea.js:2:871038) at Tl (https://ansiblecontroller-dev.company.com/static/js/main.359f10ea.js:2:870966) at El (https://ansiblecontroller-dev.company.com/static/js/main.359f10ea.js:2:870829) at yl (https://ansiblecontroller-dev.company.com/static/js/main.359f10ea.js:2:867795) at https://ansiblecontroller-dev.company.com/static/js/main.359f10ea.js:2:817240 at t.unstable_runWithPriority (https://ansiblecontroller-dev.company.com/static/js/main.359f10ea.js:2:913546) at Gi (https://ansiblecontroller-dev.company.com/static/js/main.359f10ea.js:2:817017)
 
 
The playbook runs successfully.
 
The following is in the main playbook.
  roles:
    - {role: infra.controller_configuration.job_templates, when: controller_templates is defined}
 
- name: Create job
  ansible.builtin.include_role:
    name: infra.controller_configuration.job_templates
  vars:
    controller_templates: "{{ data }}"
  no_log: false
 
The following is the .project file:
---
- name: OnPrem-Server-Teardown-Manual-Test
  credentials:
    - serviceuser1
    - OnpremServerBuild-vault
  project: OS-Build-jctesting
  inventory: Localhost Automation
  execution_environment: ee-serverbuild-automation
  playbook: teardown-new.yml
  organization: GBSAuto
  extra_vars: {
    InfobloxBaseUri: "https://ansiblecontroller.company.com/",
    infoblox_job_template_id: 401
  }
  survey_enabled: true
  survey_spec: {
    name: "Teardown Server",
    description: "This survey will gather information needed to teardown a server",
    spec: [
      {
        type: "multiselect",
        "min": 0,
        "max": 0,
        question_name: "Which tasks to run?",
        question_description: " ",
        variable: "teardown_options",
        choices: ["all", "remove_dns", "poweroff_vm", "delete_vm", "remove_satellite", "remove_computer_AD", "remove_winaccess", "remove_sccm"],
        required: true
      },
      {
        type: "multiplechoice",
        "min": 0,
        "max": 0,
        question_name: "Is this a virtual server?",
        question_description: " ",
        variable: "virtual",
        choices: ["yes", "no"],
        required: true
      },
      {
        type: "text",
        question_name: "Server Name",
        question_description: " ",
        variable: "vm",
        "min": 0,
        "max": 20,
        required: true
      },
      {
        type: "multiplechoice",
        "min": 0,
        "max": 0,
        question_name: "Site",
        question_description: " ",
        required: true,
        variable: "site",
        choices: ["SITE1", "SITE2"]
      },
      {
        type: "multiplechoice",
        "min": 0,
        "max": 0,
        question_name: "Domain",
        question_description: " ",
        required: true,
        variable: "domain",
        choices: ["domain1.com", "domain2.com", "domain3.com"]
      },
      {
        type: "multiplechoice",
        "min": 0,
        "max": 0,
        question_name: "Environment",
        question_description: " ",
        required: true,
        variable: "env",
        choices: ["prod", "dev", "sandbox"]
      }
    ]
  }
 
- playbook / task
- configuration file / list
- error
 

 
```console (error)
 
```
 
## STEPS TO REPRODUCE
 

 

 
The playbook runs successfully and the template does get created in AAP. You just can't view or change the survey. The Web interface shows There was an error loading this content. Please reload the page.
You are able to launch the template and the survey does show up. You just can't do any manual updates to it.
 
```yaml (playbook/task)
 
```
 
```yaml (config/list/array/variables)
 
```

**Comment by djdanielsson** [comment]
is this in AAP 2.4 or 2.5?

**Comment by jpadron-am** [comment]
> is this in AAP 2.4 or 2.5?

2.4

**Comment by djdanielsson** [comment]
moving this to the controller_configuration repo from aap_configuration. I would have to try and test passing this directly to the modules and see if that replicates the issue you are seeing or not

**Comment by djdanielsson** [comment]
@sean-m-sullivan or @Tompage1994 if either of you have some time to look into this as well that would be helpful

**Comment by kakashiiMF** [comment]
Anyone looked at this? Im seeing a reference of this issue in a commit, but i dont think it is resolved right?

**Comment by djdanielsson** [comment]
I am not sure if it is still an issue or not. Are you having similar error(s)?

**Comment by kakashiiMF** [comment]
> I am not sure if it is still an issue or not. Are you having similar error(s)?

Yap, exactly the same problem as described in this issue still happens in the last version of 2.4.

Btw, in the documentation i see some examples (here: https://github.com/redhat-cop/infra.controller_configuration/blob/3.1.3/roles/job_templates/README.md) using "\n" like this:

<img width="529" height="792" alt="Image" src="https://github.com/user-attachments/assets/d9860397-f035-4737-aed5-c6a6dda54a17" />

But I found that choices can be provided as a list of items, but they cannot be booleans. In the GUI it’s not possible to select true or false. The choice items need to be strings or numbers — I’m not sure why. I can open a separate issue for this if you’d like, since I think it’s unrelated to the original problem.

**Comment by djdanielsson** [comment]
yes let's open a different issue for that

**Comment by kakashiiMF** [comment]
> yes let's open a different issue for that

Okay, perfect. Do you want me to share more info about this issue? I can replicate it and show you a few more examples.

**Comment by djdanielsson** [comment]
Yes please

**Comment by kakashiiMF** [comment]
So in my job template via CaC has this configuration:

GET /api/v2/job_templates/1027/survey_spec/

HTTP 200 OK
Allow: GET, POST, DELETE, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept
X-API-Node: lxaapctrq2.qly.aap.sys.sibs.pt
X-API-Product-Name: Red Hat Ansible Automation Platform
X-API-Product-Version: 4.5.24
X-API-Time: 0.029s

{
    "name": "Inputs",
    "spec": [
        {
            "max": 0,
            "min": 0,
            "type": "multiplechoice",
            "choices": [
                "get",
                "update",
                "reset"
            ],
            "required": true,
            "variable": "error_handler_operation",
            "new_question": true,
            "question_name": "Select operation type:",
            "question_description": "Operation type to control"
        },
        {
            "max": 128,
            "min": 0,
            "type": "text",
            "required": false,
            "variable": "system_name",
            "new_question": true,
            "question_name": "Select system name:",
            "question_description": "System name of central log"
        },
        {
            "max": 128,
            "min": 0,
            "type": "text",
            "required": false,
            "variable": "system_function_domain",
            "new_question": true,
            "question_name": "Select system function domain:",
            "question_description": "System function domain of central log"
        },
        {
            "max": 128,
            "min": 0,
            "type": "text",
            "required": false,
            "variable": "system_function_type",
            "new_question": true,
            "question_name": "Select system function type:",
            "question_description": "System function type of central log"
        },
        {
            "max": 128,
            "min": 0,
            "type": "text",
            "required": false,
            "variable": "system_function",
            "new_question": true,
            "question_name": "Select system function:",
            "question_description": "System function of central log"
        },
        {
            "max": 128,
            "min": 0,
            "type": "text",
            "required": false,
            "variable": "system_function_operation",
            "new_question": true,
            "question_name": "Select system function operation:",
            "question_description": "System function operation of central log"
        },
        {
            "max": 128,
            "min": 0,
            "type": "text",
            "required": false,
            "variable": "system_function_native_code",
            "new_question": true,
            "question_name": "Select system function native code:",
            "question_description": "System function native code of central log"
        },
        {
            "max": 128,
            "min": 0,
            "type": "text",
            "required": false,
            "variable": "status_code",
            "new_question": true,
            "question_name": "Select status code:",
            "question_description": "Status code code of central log"
        }
    ],
    "description": "Inputs to control the error handler configurations"
}

In the GUI you can check this in here:

<img width="1662" height="791" alt="Image" src="https://github.com/user-attachments/assets/fb72ad07-21fe-4572-98d3-8769cc11c243" />

I can edit any of the fields that are the type of "text". But when i click in the type multiplechoice it return this error:

<img width="952" height="456" alt="Image" src="https://github.com/user-attachments/assets/ac5e3ec9-d09e-4370-adeb-c148d1c23564" />

Now i created another template using the GUI:

GET /api/v2/job_templates/1668/survey_spec/

HTTP 200 OK
Allow: GET, POST, DELETE, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept
X-API-Node: lxaapctrq2.qly.aap.sys.sibs.pt
X-API-Product-Name: Red Hat Ansible Automation Platform
X-API-Product-Version: 4.5.24
X-API-Time: 0.034s

{
    "name": "",
    "spec": [
        {
            "max": 1024,
            "min": 0,
            "type": "multiplechoice",
            "choices": [
                "asdg",
                "asdsgfd",
                "asdgfd",
                "asd"
            ],
            "default": "",
            "required": true,
            "variable": "teste",
            "new_question": true,
            "question_name": "teste1",
            "question_description": ""
        }
    ],
    "description": ""
}

<img width="1686" height="352" alt="Image" src="https://github.com/user-attachments/assets/f88a945a-5777-4f59-8642-43d6e62d387f" />

And i can edit this survey:

<img width="1665" height="519" alt="Image" src="https://github.com/user-attachments/assets/0a684189-9cba-47df-bb9b-1f777afc087f" />

Can u check this error then?

**Comment by kakashiiMF** [comment]
Okay, i debugged a little more, and i found out that i had 2 differences between the survey's:

max:0 vs max:1024
and
without default: "" vs with default: ""

With only max:1024 and without default: "" still doesnt work.
With max:0 and with default: "", tt seems, what is missing in the survey spec is the default: "" because with that it works... But now, i think that it is still a bug, and default it should be always empty.

Can you help? :)
